name: tracker_costs
description: "Wish List App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.1
  
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3 
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true